version: '3.9'
services:
    db:
        image: mysql:8.0.21
        container_name: docmanagement_db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: docmanagement
            MYSQL_ROOT_PASSWORD: lvrkrft
            TZ: UTC
        ports: 
            - "3307:3306"
        volumes:
            - mysql_volume:/data
volumes:
    mysql_volume:
